version: '3.6'
services:
  elasticsearch:
    #image: docker.elastic.co/elasticsearch/elasticsearch:5.5.3
    build:
      context: .
      dockerfile: dockerfiles/Elasticsearch.Dockerfile
    container_name: elasticsearch
    environment:
      - node.name=winner
      - cluster.name=docker-cluster
      #- bootstrap.memory_lock=true
      - bootstrap.memory_lock=true
      - network.host=0.0.0.0
      - discovery.zen.minimum_master_nodes=1
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    deploy:
      resources:
        limits: 
          memory: 1g
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200
    networks:
      - elasticsearch_553_net

volumes:
  esdata:

networks:
  elasticsearch_553_net:
    external: true

